# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveplaylist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmlscraper',
            name='title_xpaths',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
