# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liveplaylist', '0005_auto_20160804_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delete_obsolete_streams', models.BooleanField(default=True)),
                ('livechannel_naming', models.IntegerField(choices=[(None, 'Full title_xpaths'), (0, 'First title_xpath'), (1, 'Second title_xpath'), (2, 'Third title_xpath')])),
                ('htmlscrapers', models.ManyToManyField(to='liveplaylist.HTMLScraper')),
            ],
        ),
        migrations.AlterField(
            model_name='playlist',
            name='channel_naming',
            field=models.CharField(choices=[('%(playlist)s - %(channel)s', '<Name Playlist> - <Name Kanal>'), ('%(playlist)s - %(position)d', '<Name Playlist> - <Position Kanal>'), ('%(playlist)s - %(position)d - %(channel)s', '<Name Playlist> - <Position Kanal> - <Name Kanal>'), ('%(playlist)s - %(extra)s %(position)d - %(channel)s', '<Name Playlist> - <Extra> <Position Kanal> - <Name Kanal>')], max_length=255),
        ),
        migrations.AddField(
            model_name='playlistupdate',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liveplaylist.Playlist'),
        ),
    ]
