# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveplaylist', '0006_auto_20160804_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmlscraper',
            name='main_page_find_stream_xpath',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='htmlscraper',
            name='main_page_find_subpages_xpath',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='htmlscraper',
            name='subpage_find_stream_xpath',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='channel_naming',
            field=models.CharField(choices=[('%(channel)s', '<Name Kanal>'), ('%(playlist)s - %(channel)s', '<Name Playlist> - <Name Kanal>'), ('%(playlist)s - %(position)d', '<Name Playlist> - <Position Kanal>'), ('%(playlist)s - %(position)d - %(channel)s', '<Name Playlist> - <Position Kanal> - <Name Kanal>'), ('%(playlist)s - %(extra)s %(position)d - %(channel)s', '<Name Playlist> - <Extra> <Position Kanal> - <Name Kanal>')], max_length=255),
        ),
    ]
