# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-05 20:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveplaylist', '0007_auto_20160805_1619'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='htmlscraper',
            options={'ordering': ('name', 'main_page_url')},
        ),
        migrations.AddField(
            model_name='htmlscraper',
            name='display_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='channel_naming',
            field=models.CharField(choices=[('%(channel)s', '<Name Kanal>'), ('%(playlist)s - %(channel)s', '<Name Playlist> - <Name Kanal>'), ('%(scraper)s - %(channel)s', '<Name Scraper> - <Name Kanal>'), ('%(playlist)s - %(position)d', '<Name Playlist> - <Position Kanal>'), ('%(playlist)s - %(position)d - %(channel)s', '<Name Playlist> - <Position Kanal> - <Name Kanal>'), ('%(playlist)s - %(extra)s %(position)d - %(channel)s', '<Name Playlist> - <Extra> <Position Kanal> - <Name Kanal>')], max_length=255),
        ),
    ]
