# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveplaylist', '0008_auto_20160805_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmlscraper',
            name='scraper_type',
            field=models.CharField(blank=True, choices=[('ZDFScraperPage', 'ZDFScraperPage')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='livesource',
            name='end_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livesource',
            name='start_dt',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
