# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liveplaylist', '0009_auto_20160808_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcewrapper',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
