# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 11:29
from __future__ import unicode_literals

from django.db import migrations, models
import liveplaylist.validators


class Migration(migrations.Migration):

    dependencies = [
        ('liveplaylist', '0010_auto_20160809_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcewrapper',
            name='stream_url_wrap',
            field=models.CharField(default='%(stream_url)s', max_length=500, validators=[liveplaylist.validators.validate_wrapper_string]),
        ),
    ]
